{"ast":null,"code":"import { jsxDEV as _jsxDEV } from \"react/jsx-dev-runtime\";\n\nvar _jsxFileName = \"D:\\\\GitHub\\\\Cards\\\\client\\\\src\\\\pages\\\\test.js\",\n    _s = $RefreshSig$();\n\nimport React, { useState, useEffect } from 'react';\n\nfunction MyComponent() {\n  _s();\n\n  const [error, setError] = useState(null);\n  const [isLoaded, setIsLoaded] = useState(false);\n  const [items, setItems] = useState([]); // Примечание: пустой массив зависимостей [] означает, что\n  // этот useEffect будет запущен один раз\n  // аналогично componentDidMount()\n\n  useEffect(() => {\n    fetch(\"http://127.0.0.1:5000/?page=1\").then(res => res.json()).then(result => {\n      setIsLoaded(true);\n      setItems(result);\n    }, // Примечание: важно обрабатывать ошибки именно здесь, а не в блоке catch(),\n    // чтобы не перехватывать исключения из ошибок в самих компонентах.\n    error => {\n      setIsLoaded(true);\n      setError(error);\n    });\n  }, []);\n  return /*#__PURE__*/_jsxDEV(\"p\", {\n    children: items.map(item => item.first_name)\n  }, void 0, false, {\n    fileName: _jsxFileName,\n    lineNumber: 29,\n    columnNumber: 9\n  }, this);\n}\n\n_s(MyComponent, \"m9AscAN57M/MODoTwSsNC5AuztA=\");\n\n_c = MyComponent;\nexport default MyComponent;\n\nvar _c;\n\n$RefreshReg$(_c, \"MyComponent\");","map":{"version":3,"sources":["D:/GitHub/Cards/client/src/pages/test.js"],"names":["React","useState","useEffect","MyComponent","error","setError","isLoaded","setIsLoaded","items","setItems","fetch","then","res","json","result","map","item","first_name"],"mappings":";;;;;AAAA,OAAOA,KAAP,IAAgBC,QAAhB,EAA2BC,SAA3B,QAA4C,OAA5C;;AAEA,SAASC,WAAT,GAAuB;AAAA;;AACnB,QAAM,CAACC,KAAD,EAAQC,QAAR,IAAoBJ,QAAQ,CAAC,IAAD,CAAlC;AACA,QAAM,CAACK,QAAD,EAAWC,WAAX,IAA0BN,QAAQ,CAAC,KAAD,CAAxC;AACA,QAAM,CAACO,KAAD,EAAQC,QAAR,IAAoBR,QAAQ,CAAC,EAAD,CAAlC,CAHmB,CAKnB;AACA;AACA;;AACAC,EAAAA,SAAS,CAAC,MAAM;AACdQ,IAAAA,KAAK,CAAC,+BAAD,CAAL,CACGC,IADH,CACQC,GAAG,IAAIA,GAAG,CAACC,IAAJ,EADf,EAEGF,IAFH,CAGKG,MAAD,IAAY;AACVP,MAAAA,WAAW,CAAC,IAAD,CAAX;AACAE,MAAAA,QAAQ,CAACK,MAAD,CAAR;AACD,KANL,EAOI;AACA;AACCV,IAAAA,KAAD,IAAW;AACTG,MAAAA,WAAW,CAAC,IAAD,CAAX;AACAF,MAAAA,QAAQ,CAACD,KAAD,CAAR;AACD,KAZL;AAcD,GAfQ,EAeN,EAfM,CAAT;AAiBA,sBACI;AAAA,cAAII,KAAK,CAACO,GAAN,CAAUC,IAAI,IAAIA,IAAI,CAACC,UAAvB;AAAJ;AAAA;AAAA;AAAA;AAAA,UADJ;AAGH;;GA5BQd,W;;KAAAA,W;AA8BT,eAAeA,WAAf","sourcesContent":["import React, { useState,  useEffect } from 'react';\r\n\r\nfunction MyComponent() {\r\n    const [error, setError] = useState(null);\r\n    const [isLoaded, setIsLoaded] = useState(false);\r\n    const [items, setItems] = useState([]);\r\n  \r\n    // Примечание: пустой массив зависимостей [] означает, что\r\n    // этот useEffect будет запущен один раз\r\n    // аналогично componentDidMount()\r\n    useEffect(() => {\r\n      fetch(\"http://127.0.0.1:5000/?page=1\")\r\n        .then(res => res.json())\r\n        .then(\r\n          (result) => {\r\n            setIsLoaded(true);\r\n            setItems(result);\r\n          },\r\n          // Примечание: важно обрабатывать ошибки именно здесь, а не в блоке catch(),\r\n          // чтобы не перехватывать исключения из ошибок в самих компонентах.\r\n          (error) => {\r\n            setIsLoaded(true);\r\n            setError(error);\r\n          }\r\n        )\r\n    }, [])\r\n  \r\n    return (\r\n        <p>{items.map(item => item.first_name)}</p>\r\n    )\r\n}\r\n\r\nexport default MyComponent;"]},"metadata":{},"sourceType":"module"}